Created a house price prediction model using Zillow data, incorporating advanced machine learning techniques to analyze factors like location, square footage, number of bedrooms, and market conditions. The model aims to predict home prices with high accuracy, offering valuable insights for real estate investors, buyers, and sellers to optimize their decision-making processes and stay ahead of market trends.

In [102]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt 
import seaborn as sns

In [74]:
dataset = pd.read_csv((r'C:\Users\shikha.gupta.LT-INTERN08\Desktop\Dataset\Housing.csv'))

In [104]:
df = pd.DataFrame(dataset)

In [106]:
dataset

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,10542000.0,7420.0,4,2,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
1,10542000.0,8960.0,4,3,4,NaN,NaN,NaN,NaN,NaN,3,no,NaN
2,10542000.0,9960.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
3,10542000.0,7500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,3,yes,NaN
4,10542000.0,7420.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
5,10542000.0,7500.0,3,3,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
6,10150000.0,8580.0,4,3,4,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
7,10150000.0,12543.6,5,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
8,9870000.0,8100.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
9,9800000.0,5750.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
10,9800000.0,12543.6,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
11,9681000.0,6000.0,4,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
12,9310000.0,6550.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
13,9240000.0,3500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
14,9240000.0,7800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
15,9100000.0,6000.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
16,9100000.0,6600.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
17,8960000.0,8500.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
18,8890000.0,4600.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
19,8855000.0,6420.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
20,8750000.0,4320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
21,8680000.0,7155.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
22,8645000.0,8050.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
23,8645000.0,4560.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
24,8575000.0,8800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
25,8540000.0,6540.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
26,8463000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
27,8400000.0,8875.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
28,8400000.0,7950.0,5,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
29,8400000.0,5500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
30,8400000.0,7475.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
31,8400000.0,7000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
32,8295000.0,4880.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
33,8190000.0,5960.0,3,3,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
34,8120000.0,6840.0,5,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
35,8080940.0,7000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
36,8043000.0,7482.0,3,2,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
37,7980000.0,9000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
38,7962500.0,6000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
39,7910000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
40,7875000.0,6550.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
41,7840000.0,6360.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
42,7700000.0,6480.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
43,7700000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
44,7560000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
45,7560000.0,6000.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
46,7525000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
47,7490000.0,6600.0,3,1,4,NaN,NaN,NaN,NaN,NaN,3,yes,NaN
48,7455000.0,4300.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
49,7420000.0,7440.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
50,7420000.0,7440.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
51,7420000.0,6325.0,3,1,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
52,7350000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
53,7350000.0,5150.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
54,7350000.0,6000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
55,7350000.0,6000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
56,7343000.0,11440.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
57,7245000.0,9000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
58,7210000.0,7680.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
59,7210000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
60,7140000.0,6000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
61,7070000.0,8880.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
62,7070000.0,6240.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
63,7035000.0,6360.0,4,2,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
64,7000000.0,11175.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
65,6930000.0,8880.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
66,6930000.0,12543.6,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
67,6895000.0,7700.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
68,6860000.0,6000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
69,6790000.0,12090.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
70,6790000.0,4000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
71,6755000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
72,6720000.0,5020.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
73,6685000.0,6600.0,2,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
74,6650000.0,4040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
75,6650000.0,4260.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
76,6650000.0,6420.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
77,6650000.0,6500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
78,6650000.0,5700.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
79,6650000.0,6000.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
80,6629000.0,6000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
81,6615000.0,4000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
82,6615000.0,10500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
83,6580000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
84,6510000.0,3760.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
85,6510000.0,8250.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
86,6510000.0,6670.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
87,6475000.0,3960.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
88,6475000.0,7410.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
89,6440000.0,8580.0,5,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
90,6440000.0,5000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
91,6419000.0,6750.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
92,6405000.0,4800.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
93,6300000.0,7200.0,3,2,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
94,6300000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
95,6300000.0,4100.0,3,2,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
96,6300000.0,9000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
97,6300000.0,6400.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
98,6293000.0,6600.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
99,6265000.0,6000.0,4,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
100,6230000.0,6600.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
101,6230000.0,5500.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
102,6195000.0,5500.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
103,6195000.0,6350.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
104,6195000.0,5500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
105,6160000.0,4500.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
106,6160000.0,5450.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
107,6125000.0,6420.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
108,6107500.0,3240.0,4,1,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
109,6090000.0,6615.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
110,6090000.0,6600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
111,6090000.0,8372.0,3,1,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
112,6083000.0,4300.0,5,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
113,6083000.0,9620.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
114,6020000.0,6800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
115,6020000.0,8000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
116,6020000.0,6900.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
117,5950000.0,3700.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
118,5950000.0,6420.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
119,5950000.0,7020.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
120,5950000.0,6540.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
121,5950000.0,7231.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
122,5950000.0,6254.0,4,2,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
123,5950000.0,7320.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
124,5950000.0,6525.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
125,5943000.0,12543.6,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
126,5880000.0,7160.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
127,5880000.0,6500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
128,5873000.0,5500.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
129,5873000.0,11460.0,3,1,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
130,5866000.0,4800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
131,5810000.0,5828.0,4,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
132,5810000.0,5200.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
133,5810000.0,4800.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
134,5803000.0,7000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
135,5775000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
136,5740000.0,5400.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
137,5740000.0,4640.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
138,5740000.0,5000.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
139,5740000.0,6360.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
140,5740000.0,5800.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
141,5652500.0,6660.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
142,5600000.0,10500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
143,5600000.0,4800.0,5,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
144,5600000.0,4700.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
145,5600000.0,5000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
146,5600000.0,10500.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
147,5600000.0,5500.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
148,5600000.0,6360.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
149,5600000.0,6600.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
150,5600000.0,5136.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
151,5565000.0,4400.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
152,5565000.0,5400.0,5,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
153,5530000.0,3300.0,3,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
154,5530000.0,3650.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
155,5530000.0,6100.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
156,5523000.0,6900.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
157,5495000.0,2817.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
158,5495000.0,7980.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
159,5460000.0,3150.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
160,5460000.0,6210.0,4,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
161,5460000.0,6100.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
162,5460000.0,6600.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
163,5425000.0,6825.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
164,5390000.0,6710.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
165,5383000.0,6450.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
166,5320000.0,7800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
167,5285000.0,4600.0,2,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
168,5250000.0,4260.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
169,5250000.0,6540.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
170,5250000.0,5500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
171,5250000.0,10269.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
172,5250000.0,8400.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
173,5250000.0,5300.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
174,5250000.0,3800.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
175,5250000.0,9800.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
176,5250000.0,8520.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
177,5243000.0,6050.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
178,5229000.0,7085.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
179,5215000.0,3180.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
180,5215000.0,4500.0,4,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
181,5215000.0,7200.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
182,5145000.0,3410.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
183,5145000.0,7980.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
184,5110000.0,3000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
185,5110000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
186,5110000.0,11410.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
187,5110000.0,6100.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
188,5075000.0,5720.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
189,5040000.0,3540.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
190,5040000.0,7600.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
191,5040000.0,10700.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
192,5040000.0,6600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
193,5033000.0,4800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
194,5005000.0,8150.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
195,4970000.0,4410.0,4,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
196,4970000.0,7686.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
197,4956000.0,2800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
198,4935000.0,5948.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
199,4907000.0,4200.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
200,4900000.0,4520.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
201,4900000.0,4095.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
202,4900000.0,4120.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
203,4900000.0,5400.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
204,4900000.0,4770.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
205,4900000.0,6300.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
206,4900000.0,5800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
207,4900000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
208,4900000.0,2970.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
209,4900000.0,6720.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
210,4900000.0,4646.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
211,4900000.0,12543.6,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
212,4893000.0,3420.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
213,4893000.0,4995.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
214,4865000.0,4350.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
215,4830000.0,4160.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
216,4830000.0,6040.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
217,4830000.0,6862.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
218,4830000.0,4815.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
219,4795000.0,7000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
220,4795000.0,8100.0,4,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
221,4767000.0,3420.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
222,4760000.0,9166.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
223,4760000.0,6321.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
224,4760000.0,10240.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
225,4753000.0,6440.0,2,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
226,4690000.0,5170.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
227,4690000.0,6000.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
228,4690000.0,3630.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
229,4690000.0,9667.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
230,4690000.0,5400.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
231,4690000.0,4320.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
232,4655000.0,3745.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
233,4620000.0,4160.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
234,4620000.0,3880.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
235,4620000.0,5680.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
236,4620000.0,2870.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
237,4620000.0,5010.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
238,4613000.0,4510.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
239,4585000.0,4000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
240,4585000.0,3840.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
241,4550000.0,3760.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
242,4550000.0,3640.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
243,4550000.0,2550.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
244,4550000.0,5320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
245,4550000.0,5360.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
246,4550000.0,3520.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
247,4550000.0,8400.0,4,1,4,NaN,NaN,NaN,NaN,NaN,3,no,NaN
248,4543000.0,4100.0,2,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
249,4543000.0,4990.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
250,4515000.0,3510.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
251,4515000.0,3450.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
252,4515000.0,9860.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
253,4515000.0,3520.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
254,4480000.0,4510.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
255,4480000.0,5885.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
256,4480000.0,4000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
257,4480000.0,8250.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
258,4480000.0,4040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
259,4473000.0,6360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
260,4473000.0,3162.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
261,4473000.0,3510.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
262,4445000.0,3750.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
263,4410000.0,3968.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
264,4410000.0,4900.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
265,4403000.0,2880.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
266,4403000.0,4880.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
267,4403000.0,4920.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
268,4382000.0,4950.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
269,4375000.0,3900.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
270,4340000.0,4500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
271,4340000.0,1972.0,5,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
272,4340000.0,4075.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
273,4340000.0,3500.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
274,4340000.0,6450.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
275,4319000.0,4032.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
276,4305000.0,4400.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
277,4305000.0,10360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
278,4277000.0,3400.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
279,4270000.0,6360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
280,4270000.0,6360.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
281,4270000.0,4500.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
282,4270000.0,2175.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
283,4270000.0,4360.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
284,4270000.0,7770.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
285,4235000.0,6650.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
286,4235000.0,2787.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
287,4200000.0,5500.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
288,4200000.0,5040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
289,4200000.0,5850.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
290,4200000.0,2610.0,4,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
291,4200000.0,2953.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
292,4200000.0,2747.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
293,4200000.0,4410.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
294,4200000.0,4000.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
295,4200000.0,2325.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
296,4200000.0,4600.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
297,4200000.0,3640.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
298,4200000.0,5800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
299,4200000.0,7000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
300,4200000.0,4079.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
301,4200000.0,3520.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
302,4200000.0,2145.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
303,4200000.0,4500.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
304,4193000.0,8250.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
305,4193000.0,3450.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
306,4165000.0,4840.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
307,4165000.0,4080.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
308,4165000.0,4046.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
309,4130000.0,4632.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
310,4130000.0,5985.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
311,4123000.0,6060.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
312,4098500.0,3600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
313,4095000.0,3680.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
314,4095000.0,4040.0,2,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
315,4095000.0,5600.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
316,4060000.0,5900.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
317,4060000.0,4992.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
318,4060000.0,4340.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
319,4060000.0,3000.0,4,1,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
320,4060000.0,4320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
321,4025000.0,3630.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
322,4025000.0,3460.0,3,2,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
323,4025000.0,5400.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
324,4007500.0,4500.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
325,4007500.0,3460.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
326,3990000.0,4100.0,4,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
327,3990000.0,6480.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
328,3990000.0,4500.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
329,3990000.0,3960.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
330,3990000.0,4050.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
331,3920000.0,7260.0,3,2,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
332,3920000.0,5500.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
333,3920000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
334,3920000.0,3290.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
335,3920000.0,3816.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
336,3920000.0,8080.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
337,3920000.0,2145.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
338,3885000.0,3780.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
339,3885000.0,3180.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
340,3850000.0,5300.0,5,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
341,3850000.0,3180.0,2,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
342,3850000.0,7152.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
343,3850000.0,4080.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
344,3850000.0,3850.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
345,3850000.0,2015.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
346,3850000.0,2176.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
347,3836000.0,3350.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
348,3815000.0,3150.0,2,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
349,3780000.0,4820.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
350,3780000.0,3420.0,2,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
351,3780000.0,3600.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
352,3780000.0,5830.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
353,3780000.0,2856.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN

In [107]:
pd.set_option('display.max_rows', None)
dataset

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,10542000.0,7420.0,4,2,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
1,10542000.0,8960.0,4,3,4,NaN,NaN,NaN,NaN,NaN,3,no,NaN
2,10542000.0,9960.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
3,10542000.0,7500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,3,yes,NaN
4,10542000.0,7420.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
5,10542000.0,7500.0,3,3,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
6,10150000.0,8580.0,4,3,4,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
7,10150000.0,12543.6,5,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
8,9870000.0,8100.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
9,9800000.0,5750.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
10,9800000.0,12543.6,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
11,9681000.0,6000.0,4,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
12,9310000.0,6550.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
13,9240000.0,3500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
14,9240000.0,7800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
15,9100000.0,6000.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
16,9100000.0,6600.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
17,8960000.0,8500.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
18,8890000.0,4600.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
19,8855000.0,6420.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
20,8750000.0,4320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
21,8680000.0,7155.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
22,8645000.0,8050.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
23,8645000.0,4560.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
24,8575000.0,8800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
25,8540000.0,6540.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
26,8463000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
27,8400000.0,8875.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
28,8400000.0,7950.0,5,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
29,8400000.0,5500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
30,8400000.0,7475.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
31,8400000.0,7000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
32,8295000.0,4880.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
33,8190000.0,5960.0,3,3,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
34,8120000.0,6840.0,5,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
35,8080940.0,7000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
36,8043000.0,7482.0,3,2,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
37,7980000.0,9000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
38,7962500.0,6000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
39,7910000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
40,7875000.0,6550.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
41,7840000.0,6360.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
42,7700000.0,6480.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
43,7700000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
44,7560000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
45,7560000.0,6000.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
46,7525000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
47,7490000.0,6600.0,3,1,4,NaN,NaN,NaN,NaN,NaN,3,yes,NaN
48,7455000.0,4300.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
49,7420000.0,7440.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
50,7420000.0,7440.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
51,7420000.0,6325.0,3,1,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
52,7350000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
53,7350000.0,5150.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
54,7350000.0,6000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
55,7350000.0,6000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
56,7343000.0,11440.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
57,7245000.0,9000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
58,7210000.0,7680.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
59,7210000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
60,7140000.0,6000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
61,7070000.0,8880.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
62,7070000.0,6240.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
63,7035000.0,6360.0,4,2,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
64,7000000.0,11175.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
65,6930000.0,8880.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
66,6930000.0,12543.6,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
67,6895000.0,7700.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
68,6860000.0,6000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
69,6790000.0,12090.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
70,6790000.0,4000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
71,6755000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
72,6720000.0,5020.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
73,6685000.0,6600.0,2,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
74,6650000.0,4040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
75,6650000.0,4260.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
76,6650000.0,6420.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
77,6650000.0,6500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
78,6650000.0,5700.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
79,6650000.0,6000.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
80,6629000.0,6000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
81,6615000.0,4000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
82,6615000.0,10500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
83,6580000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
84,6510000.0,3760.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
85,6510000.0,8250.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
86,6510000.0,6670.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
87,6475000.0,3960.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
88,6475000.0,7410.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
89,6440000.0,8580.0,5,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
90,6440000.0,5000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
91,6419000.0,6750.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
92,6405000.0,4800.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
93,6300000.0,7200.0,3,2,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
94,6300000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
95,6300000.0,4100.0,3,2,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
96,6300000.0,9000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
97,6300000.0,6400.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
98,6293000.0,6600.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
99,6265000.0,6000.0,4,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
100,6230000.0,6600.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
101,6230000.0,5500.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
102,6195000.0,5500.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
103,6195000.0,6350.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
104,6195000.0,5500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
105,6160000.0,4500.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
106,6160000.0,5450.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
107,6125000.0,6420.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
108,6107500.0,3240.0,4,1,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
109,6090000.0,6615.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
110,6090000.0,6600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
111,6090000.0,8372.0,3,1,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
112,6083000.0,4300.0,5,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
113,6083000.0,9620.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
114,6020000.0,6800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
115,6020000.0,8000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
116,6020000.0,6900.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
117,5950000.0,3700.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
118,5950000.0,6420.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
119,5950000.0,7020.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
120,5950000.0,6540.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
121,5950000.0,7231.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
122,5950000.0,6254.0,4,2,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
123,5950000.0,7320.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
124,5950000.0,6525.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
125,5943000.0,12543.6,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
126,5880000.0,7160.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
127,5880000.0,6500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
128,5873000.0,5500.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
129,5873000.0,11460.0,3,1,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
130,5866000.0,4800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
131,5810000.0,5828.0,4,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
132,5810000.0,5200.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
133,5810000.0,4800.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
134,5803000.0,7000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
135,5775000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
136,5740000.0,5400.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
137,5740000.0,4640.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
138,5740000.0,5000.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
139,5740000.0,6360.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
140,5740000.0,5800.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
141,5652500.0,6660.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
142,5600000.0,10500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
143,5600000.0,4800.0,5,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
144,5600000.0,4700.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
145,5600000.0,5000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
146,5600000.0,10500.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
147,5600000.0,5500.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
148,5600000.0,6360.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
149,5600000.0,6600.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
150,5600000.0,5136.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
151,5565000.0,4400.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
152,5565000.0,5400.0,5,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
153,5530000.0,3300.0,3,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
154,5530000.0,3650.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
155,5530000.0,6100.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
156,5523000.0,6900.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
157,5495000.0,2817.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
158,5495000.0,7980.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
159,5460000.0,3150.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
160,5460000.0,6210.0,4,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
161,5460000.0,6100.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
162,5460000.0,6600.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
163,5425000.0,6825.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
164,5390000.0,6710.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
165,5383000.0,6450.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
166,5320000.0,7800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
167,5285000.0,4600.0,2,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
168,5250000.0,4260.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
169,5250000.0,6540.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
170,5250000.0,5500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
171,5250000.0,10269.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
172,5250000.0,8400.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
173,5250000.0,5300.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
174,5250000.0,3800.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
175,5250000.0,9800.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
176,5250000.0,8520.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
177,5243000.0,6050.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
178,5229000.0,7085.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
179,5215000.0,3180.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
180,5215000.0,4500.0,4,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
181,5215000.0,7200.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
182,5145000.0,3410.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
183,5145000.0,7980.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
184,5110000.0,3000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
185,5110000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
186,5110000.0,11410.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
187,5110000.0,6100.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
188,5075000.0,5720.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
189,5040000.0,3540.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
190,5040000.0,7600.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
191,5040000.0,10700.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
192,5040000.0,6600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
193,5033000.0,4800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
194,5005000.0,8150.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
195,4970000.0,4410.0,4,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
196,4970000.0,7686.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
197,4956000.0,2800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
198,4935000.0,5948.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
199,4907000.0,4200.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
200,4900000.0,4520.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
201,4900000.0,4095.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
202,4900000.0,4120.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
203,4900000.0,5400.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
204,4900000.0,4770.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
205,4900000.0,6300.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
206,4900000.0,5800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
207,4900000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
208,4900000.0,2970.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
209,4900000.0,6720.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
210,4900000.0,4646.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
211,4900000.0,12543.6,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
212,4893000.0,3420.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
213,4893000.0,4995.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
214,4865000.0,4350.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
215,4830000.0,4160.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
216,4830000.0,6040.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
217,4830000.0,6862.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
218,4830000.0,4815.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
219,4795000.0,7000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
220,4795000.0,8100.0,4,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
221,4767000.0,3420.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
222,4760000.0,9166.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
223,4760000.0,6321.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
224,4760000.0,10240.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
225,4753000.0,6440.0,2,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
226,4690000.0,5170.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
227,4690000.0,6000.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
228,4690000.0,3630.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
229,4690000.0,9667.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
230,4690000.0,5400.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
231,4690000.0,4320.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
232,4655000.0,3745.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
233,4620000.0,4160.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
234,4620000.0,3880.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
235,4620000.0,5680.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
236,4620000.0,2870.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
237,4620000.0,5010.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
238,4613000.0,4510.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
239,4585000.0,4000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
240,4585000.0,3840.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
241,4550000.0,3760.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
242,4550000.0,3640.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
243,4550000.0,2550.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
244,4550000.0,5320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
245,4550000.0,5360.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
246,4550000.0,3520.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
247,4550000.0,8400.0,4,1,4,NaN,NaN,NaN,NaN,NaN,3,no,NaN
248,4543000.0,4100.0,2,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
249,4543000.0,4990.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
250,4515000.0,3510.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
251,4515000.0,3450.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
252,4515000.0,9860.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
253,4515000.0,3520.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
254,4480000.0,4510.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
255,4480000.0,5885.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
256,4480000.0,4000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
257,4480000.0,8250.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
258,4480000.0,4040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
259,4473000.0,6360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
260,4473000.0,3162.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
261,4473000.0,3510.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
262,4445000.0,3750.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
263,4410000.0,3968.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
264,4410000.0,4900.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
265,4403000.0,2880.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
266,4403000.0,4880.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
267,4403000.0,4920.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
268,4382000.0,4950.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
269,4375000.0,3900.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
270,4340000.0,4500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
271,4340000.0,1972.0,5,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
272,4340000.0,4075.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
273,4340000.0,3500.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
274,4340000.0,6450.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
275,4319000.0,4032.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
276,4305000.0,4400.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
277,4305000.0,10360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
278,4277000.0,3400.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
279,4270000.0,6360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
280,4270000.0,6360.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
281,4270000.0,4500.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
282,4270000.0,2175.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
283,4270000.0,4360.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
284,4270000.0,7770.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
285,4235000.0,6650.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
286,4235000.0,2787.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
287,4200000.0,5500.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
288,4200000.0,5040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
289,4200000.0,5850.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
290,4200000.0,2610.0,4,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
291,4200000.0,2953.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
292,4200000.0,2747.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
293,4200000.0,4410.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
294,4200000.0,4000.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
295,4200000.0,2325.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
296,4200000.0,4600.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
297,4200000.0,3640.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
298,4200000.0,5800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
299,4200000.0,7000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
300,4200000.0,4079.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
301,4200000.0,3520.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
302,4200000.0,2145.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
303,4200000.0,4500.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
304,4193000.0,8250.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
305,4193000.0,3450.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
306,4165000.0,4840.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
307,4165000.0,4080.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
308,4165000.0,4046.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
309,4130000.0,4632.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
310,4130000.0,5985.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
311,4123000.0,6060.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
312,4098500.0,3600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
313,4095000.0,3680.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
314,4095000.0,4040.0,2,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
315,4095000.0,5600.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
316,4060000.0,5900.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
317,4060000.0,4992.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
318,4060000.0,4340.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
319,4060000.0,3000.0,4,1,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
320,4060000.0,4320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
321,4025000.0,3630.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
322,4025000.0,3460.0,3,2,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
323,4025000.0,5400.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
324,4007500.0,4500.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
325,4007500.0,3460.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
326,3990000.0,4100.0,4,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
327,3990000.0,6480.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
328,3990000.0,4500.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
329,3990000.0,3960.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
330,3990000.0,4050.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
331,3920000.0,7260.0,3,2,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
332,3920000.0,5500.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
333,3920000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
334,3920000.0,3290.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
335,3920000.0,3816.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
336,3920000.0,8080.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
337,3920000.0,2145.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
338,3885000.0,3780.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
339,3885000.0,3180.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
340,3850000.0,5300.0,5,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
341,3850000.0,3180.0,2,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
342,3850000.0,7152.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
343,3850000.0,4080.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
344,3850000.0,3850.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
345,3850000.0,2015.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
346,3850000.0,2176.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
347,3836000.0,3350.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
348,3815000.0,3150.0,2,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
349,3780000.0,4820.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
350,3780000.0,3420.0,2,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
351,3780000.0,3600.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
352,3780000.0,5830.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
353,3780000.0,2856.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN

In [110]:
print("Data Information:")
df.info()

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    float64
 1   area              545 non-null    float64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          0 non-null      float64
 6   guestroom         0 non-null      float64
 7   basement          0 non-null      float64
 8   hotwaterheating   0 non-null      float64
 9   airconditioning   0 non-null      float64
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  0 non-null      float64
dtypes: float64(8), int64(4), object(1)
memory usage: 55.5+ KB

Data Cleaning

Proper handling of missing values, outliers, and data inconsistencies

In [114]:
dataset['mainroad'] = dataset['mainroad'].map({'yes': 1, 'no': 0}) 
dataset['guestroom'] = dataset['guestroom'].map({'yes': 1, 'no': 0}) 
dataset['basement'] = dataset['basement'].map({'yes': 1, 'no': 0}) 
dataset['hotwaterheating'] = dataset['hotwaterheating'].map({'yes': 1, 'no': 0}) 
dataset['airconditioning'] = dataset['airconditioning'].map({'yes': 1, 'no': 0}) 
dataset['furnishingstatus'] = dataset['furnishingstatus'].map({'furnished': 2, 'semi-furnished': 1, 'unfurnished': 0})
dataset

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,10542000.0,7420.0,4,2,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
1,10542000.0,8960.0,4,3,4,NaN,NaN,NaN,NaN,NaN,3,no,NaN
2,10542000.0,9960.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
3,10542000.0,7500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,3,yes,NaN
4,10542000.0,7420.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
5,10542000.0,7500.0,3,3,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
6,10150000.0,8580.0,4,3,4,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
7,10150000.0,12543.6,5,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
8,9870000.0,8100.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
9,9800000.0,5750.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
10,9800000.0,12543.6,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
11,9681000.0,6000.0,4,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
12,9310000.0,6550.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
13,9240000.0,3500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
14,9240000.0,7800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
15,9100000.0,6000.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
16,9100000.0,6600.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
17,8960000.0,8500.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
18,8890000.0,4600.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
19,8855000.0,6420.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
20,8750000.0,4320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
21,8680000.0,7155.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
22,8645000.0,8050.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
23,8645000.0,4560.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
24,8575000.0,8800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
25,8540000.0,6540.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
26,8463000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
27,8400000.0,8875.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
28,8400000.0,7950.0,5,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
29,8400000.0,5500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
30,8400000.0,7475.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
31,8400000.0,7000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
32,8295000.0,4880.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
33,8190000.0,5960.0,3,3,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
34,8120000.0,6840.0,5,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
35,8080940.0,7000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
36,8043000.0,7482.0,3,2,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
37,7980000.0,9000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
38,7962500.0,6000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
39,7910000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
40,7875000.0,6550.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
41,7840000.0,6360.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
42,7700000.0,6480.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
43,7700000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
44,7560000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
45,7560000.0,6000.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
46,7525000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
47,7490000.0,6600.0,3,1,4,NaN,NaN,NaN,NaN,NaN,3,yes,NaN
48,7455000.0,4300.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
49,7420000.0,7440.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
50,7420000.0,7440.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
51,7420000.0,6325.0,3,1,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
52,7350000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
53,7350000.0,5150.0,3,2,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
54,7350000.0,6000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
55,7350000.0,6000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
56,7343000.0,11440.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
57,7245000.0,9000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
58,7210000.0,7680.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
59,7210000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
60,7140000.0,6000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
61,7070000.0,8880.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
62,7070000.0,6240.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
63,7035000.0,6360.0,4,2,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
64,7000000.0,11175.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
65,6930000.0,8880.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
66,6930000.0,12543.6,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
67,6895000.0,7700.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
68,6860000.0,6000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
69,6790000.0,12090.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
70,6790000.0,4000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
71,6755000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
72,6720000.0,5020.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
73,6685000.0,6600.0,2,2,4,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
74,6650000.0,4040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
75,6650000.0,4260.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
76,6650000.0,6420.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
77,6650000.0,6500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
78,6650000.0,5700.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
79,6650000.0,6000.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
80,6629000.0,6000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
81,6615000.0,4000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
82,6615000.0,10500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
83,6580000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
84,6510000.0,3760.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
85,6510000.0,8250.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
86,6510000.0,6670.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
87,6475000.0,3960.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
88,6475000.0,7410.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
89,6440000.0,8580.0,5,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
90,6440000.0,5000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
91,6419000.0,6750.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
92,6405000.0,4800.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
93,6300000.0,7200.0,3,2,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
94,6300000.0,6000.0,4,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
95,6300000.0,4100.0,3,2,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
96,6300000.0,9000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
97,6300000.0,6400.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
98,6293000.0,6600.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
99,6265000.0,6000.0,4,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
100,6230000.0,6600.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
101,6230000.0,5500.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
102,6195000.0,5500.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
103,6195000.0,6350.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
104,6195000.0,5500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
105,6160000.0,4500.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
106,6160000.0,5450.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
107,6125000.0,6420.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
108,6107500.0,3240.0,4,1,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
109,6090000.0,6615.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
110,6090000.0,6600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
111,6090000.0,8372.0,3,1,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
112,6083000.0,4300.0,5,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
113,6083000.0,9620.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
114,6020000.0,6800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
115,6020000.0,8000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
116,6020000.0,6900.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
117,5950000.0,3700.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
118,5950000.0,6420.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
119,5950000.0,7020.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
120,5950000.0,6540.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
121,5950000.0,7231.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
122,5950000.0,6254.0,4,2,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
123,5950000.0,7320.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
124,5950000.0,6525.0,3,2,4,NaN,NaN,NaN,NaN,NaN,1,no,NaN
125,5943000.0,12543.6,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
126,5880000.0,7160.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
127,5880000.0,6500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
128,5873000.0,5500.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
129,5873000.0,11460.0,3,1,3,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
130,5866000.0,4800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
131,5810000.0,5828.0,4,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
132,5810000.0,5200.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
133,5810000.0,4800.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
134,5803000.0,7000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
135,5775000.0,6000.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
136,5740000.0,5400.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
137,5740000.0,4640.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
138,5740000.0,5000.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
139,5740000.0,6360.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
140,5740000.0,5800.0,3,2,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
141,5652500.0,6660.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
142,5600000.0,10500.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
143,5600000.0,4800.0,5,2,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
144,5600000.0,4700.0,4,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
145,5600000.0,5000.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
146,5600000.0,10500.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
147,5600000.0,5500.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
148,5600000.0,6360.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
149,5600000.0,6600.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
150,5600000.0,5136.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
151,5565000.0,4400.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
152,5565000.0,5400.0,5,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
153,5530000.0,3300.0,3,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
154,5530000.0,3650.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
155,5530000.0,6100.0,3,2,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
156,5523000.0,6900.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
157,5495000.0,2817.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
158,5495000.0,7980.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
159,5460000.0,3150.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
160,5460000.0,6210.0,4,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
161,5460000.0,6100.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
162,5460000.0,6600.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
163,5425000.0,6825.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
164,5390000.0,6710.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
165,5383000.0,6450.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
166,5320000.0,7800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
167,5285000.0,4600.0,2,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
168,5250000.0,4260.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
169,5250000.0,6540.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
170,5250000.0,5500.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
171,5250000.0,10269.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
172,5250000.0,8400.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
173,5250000.0,5300.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
174,5250000.0,3800.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
175,5250000.0,9800.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
176,5250000.0,8520.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
177,5243000.0,6050.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
178,5229000.0,7085.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
179,5215000.0,3180.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
180,5215000.0,4500.0,4,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
181,5215000.0,7200.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
182,5145000.0,3410.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
183,5145000.0,7980.0,3,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
184,5110000.0,3000.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
185,5110000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
186,5110000.0,11410.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
187,5110000.0,6100.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
188,5075000.0,5720.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
189,5040000.0,3540.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
190,5040000.0,7600.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
191,5040000.0,10700.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
192,5040000.0,6600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
193,5033000.0,4800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
194,5005000.0,8150.0,3,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
195,4970000.0,4410.0,4,3,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
196,4970000.0,7686.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
197,4956000.0,2800.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
198,4935000.0,5948.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
199,4907000.0,4200.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
200,4900000.0,4520.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
201,4900000.0,4095.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
202,4900000.0,4120.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
203,4900000.0,5400.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
204,4900000.0,4770.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
205,4900000.0,6300.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
206,4900000.0,5800.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
207,4900000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
208,4900000.0,2970.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
209,4900000.0,6720.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
210,4900000.0,4646.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
211,4900000.0,12543.6,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
212,4893000.0,3420.0,4,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
213,4893000.0,4995.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
214,4865000.0,4350.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
215,4830000.0,4160.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
216,4830000.0,6040.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
217,4830000.0,6862.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
218,4830000.0,4815.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
219,4795000.0,7000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
220,4795000.0,8100.0,4,1,4,NaN,NaN,NaN,NaN,NaN,2,no,NaN
221,4767000.0,3420.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
222,4760000.0,9166.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
223,4760000.0,6321.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
224,4760000.0,10240.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
225,4753000.0,6440.0,2,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
226,4690000.0,5170.0,3,1,4,NaN,NaN,NaN,NaN,NaN,0,no,NaN
227,4690000.0,6000.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
228,4690000.0,3630.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
229,4690000.0,9667.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
230,4690000.0,5400.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
231,4690000.0,4320.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
232,4655000.0,3745.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
233,4620000.0,4160.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
234,4620000.0,3880.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
235,4620000.0,5680.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
236,4620000.0,2870.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
237,4620000.0,5010.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
238,4613000.0,4510.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
239,4585000.0,4000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
240,4585000.0,3840.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
241,4550000.0,3760.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
242,4550000.0,3640.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
243,4550000.0,2550.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
244,4550000.0,5320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
245,4550000.0,5360.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
246,4550000.0,3520.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
247,4550000.0,8400.0,4,1,4,NaN,NaN,NaN,NaN,NaN,3,no,NaN
248,4543000.0,4100.0,2,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
249,4543000.0,4990.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
250,4515000.0,3510.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
251,4515000.0,3450.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
252,4515000.0,9860.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
253,4515000.0,3520.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
254,4480000.0,4510.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
255,4480000.0,5885.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
256,4480000.0,4000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
257,4480000.0,8250.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
258,4480000.0,4040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
259,4473000.0,6360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
260,4473000.0,3162.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
261,4473000.0,3510.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
262,4445000.0,3750.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
263,4410000.0,3968.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
264,4410000.0,4900.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
265,4403000.0,2880.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
266,4403000.0,4880.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
267,4403000.0,4920.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
268,4382000.0,4950.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
269,4375000.0,3900.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
270,4340000.0,4500.0,3,2,3,NaN,NaN,NaN,NaN,NaN,1,no,NaN
271,4340000.0,1972.0,5,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
272,4340000.0,4075.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
273,4340000.0,3500.0,4,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
274,4340000.0,6450.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
275,4319000.0,4032.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
276,4305000.0,4400.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
277,4305000.0,10360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
278,4277000.0,3400.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
279,4270000.0,6360.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
280,4270000.0,6360.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
281,4270000.0,4500.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
282,4270000.0,2175.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
283,4270000.0,4360.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
284,4270000.0,7770.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
285,4235000.0,6650.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
286,4235000.0,2787.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
287,4200000.0,5500.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
288,4200000.0,5040.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
289,4200000.0,5850.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
290,4200000.0,2610.0,4,3,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
291,4200000.0,2953.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
292,4200000.0,2747.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
293,4200000.0,4410.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
294,4200000.0,4000.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
295,4200000.0,2325.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
296,4200000.0,4600.0,3,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
297,4200000.0,3640.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
298,4200000.0,5800.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
299,4200000.0,7000.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
300,4200000.0,4079.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,no,NaN
301,4200000.0,3520.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
302,4200000.0,2145.0,3,1,3,NaN,NaN,NaN,NaN,NaN,1,yes,NaN
303,4200000.0,4500.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
304,4193000.0,8250.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
305,4193000.0,3450.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
306,4165000.0,4840.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
307,4165000.0,4080.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
308,4165000.0,4046.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
309,4130000.0,4632.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
310,4130000.0,5985.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
311,4123000.0,6060.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
312,4098500.0,3600.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
313,4095000.0,3680.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
314,4095000.0,4040.0,2,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
315,4095000.0,5600.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
316,4060000.0,5900.0,4,2,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
317,4060000.0,4992.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
318,4060000.0,4340.0,3,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
319,4060000.0,3000.0,4,1,3,NaN,NaN,NaN,NaN,NaN,2,no,NaN
320,4060000.0,4320.0,3,1,2,NaN,NaN,NaN,NaN,NaN,2,yes,NaN
321,4025000.0,3630.0,3,2,2,NaN,NaN,NaN,NaN,NaN,2,no,NaN
322,4025000.0,3460.0,3,2,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
323,4025000.0,5400.0,3,1,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
324,4007500.0,4500.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
325,4007500.0,3460.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
326,3990000.0,4100.0,4,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
327,3990000.0,6480.0,3,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
328,3990000.0,4500.0,3,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
329,3990000.0,3960.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
330,3990000.0,4050.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
331,3920000.0,7260.0,3,2,1,NaN,NaN,NaN,NaN,NaN,3,no,NaN
332,3920000.0,5500.0,4,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
333,3920000.0,3000.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
334,3920000.0,3290.0,2,1,1,NaN,NaN,NaN,NaN,NaN,1,no,NaN
335,3920000.0,3816.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
336,3920000.0,8080.0,3,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
337,3920000.0,2145.0,4,2,1,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
338,3885000.0,3780.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
339,3885000.0,3180.0,4,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
340,3850000.0,5300.0,5,2,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
341,3850000.0,3180.0,2,2,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
342,3850000.0,7152.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
343,3850000.0,4080.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
344,3850000.0,3850.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
345,3850000.0,2015.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
346,3850000.0,2176.0,2,1,2,NaN,NaN,NaN,NaN,NaN,0,yes,NaN
347,3836000.0,3350.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
348,3815000.0,3150.0,2,2,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
349,3780000.0,4820.0,3,1,2,NaN,NaN,NaN,NaN,NaN,0,no,NaN
350,3780000.0,3420.0,2,1,2,NaN,NaN,NaN,NaN,NaN,1,no,NaN
351,3780000.0,3600.0,2,1,1,NaN,NaN,NaN,NaN,NaN,0,no,NaN
352,3780000.0,5830.0,2,1,1,NaN,NaN,NaN,NaN,NaN,2,no,NaN
353,3780000.0,2856.0,3,1,3,NaN,NaN,NaN,NaN,NaN,0,yes,NaN

In [119]:
# Handle outliers, we are using capping with in the first and 99th percentile.
def cap_outliers(df, column): 
    lower_limit = df[column].quantile(0.01)
    upper_limit = df[column].quantile(0.99)
    df[column] = np.clip(df[column], lower_limit, upper_limit)

cap_outliers(dataset, 'price')
cap_outliers(dataset, 'area')
cap_outliers(dataset, 'bedrooms')
cap_outliers(dataset, 'bathrooms')
cap_outliers(dataset, 'stories')
cap_outliers(dataset, 'mainroad')
cap_outliers(dataset, 'guestroom')
cap_outliers(dataset, 'basement')
cap_outliers(dataset, 'hotwaterheating')
cap_outliers(dataset, 'airconditioning')
cap_outliers(dataset, 'parking')
cap_outliers(dataset, 'prefarea')
cap_outliers(dataset, 'furnishingstatus')

IndentationError: unindent does not match any outer indentation level (<string>, line 5)